theme = "monokai_pro_machine" # green tint
# catpuccin, dracula_at_night, everforest_dark, monokai_pro*, rose_pine are nice aesthetically
# common pitfall: some themes don't display primary cursor well
# theme = "base16_terminal" # transparent! But need to tweak colors (too green text) and pcursor
# theme = "catppuccin" # dark grey tint; doesn't show pcursor
# theme = "monokai_pro_octagon" # grey tint
# theme = "monokai_pro_spectrum" # darker grey than octagon
# theme = "rose_pine" # dark purple, doesn't show pc well

# key cheatsheet: https://cheatography.com/hiddenmonkey/cheat-sheets/helix/
#### TODO ####
# Can I configure hotkeys to execute shell commands?
# How to give multi-command functions aliases in menu
# completions?
 
[editor]
idle-timeout = 200 # ms til idle-timers, eg autocomplete. def:400

[editor.statusline] 
left = ["spinner", "diagnostics"] # LSP activity
center = ["file-name"]
# right = ["position", "separator", "position-percentage"] # bug

[editor.lsp]
display-messages = true # display lsp progress messages below statusline

[editor.cursor-shape]
insert = "bar"
normal = "block" # by dflt, all are block
select = "underline"

[editor.file-picker]
hidden = false # don't ignore hidden files

[editor.auto-pairs] # enable automatic pair insertion. for lang-spec, use languages.toml.
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.indent-guides]
render = true # show '|' character

############
## NORMAL ##
############
# don't bind Ctrl-Alt, use those in Alacritty binds, which can collide w/ helix binds
# use space-c-space to reload and test
[keys.normal]
C-a = ["save_selection", "select_all"] # also see %
# Ctrl-o/O jump back/unmapped
# Alt-o - expand selection to parent syntax note *useful*
# e - normal. C-e/A-e unmapped.
# C-i - jump fwd
A-i = "increment"
A-I = "decrement"
d = [ "yank", "yank_joined_to_clipboard", "delete_selection"]
y = [ "yank", "yank_joined_to_clipboard"]
D = ["extend_to_line_bounds", "yank", "paste_after", "move_line_down"] # duplicate line
# alt-d deletes word in insert mode, no-yank in normal mode
# h/H - default
t = ["delete_selection", "paste_after"] # transpose chars good
T = "switch_case" 
# Ctrl-t - map to toggle menu. toggles preview in picker. 
# n/N - next/prev in search (always nxt/prev, doesn't swap like vim)
# alt-n selects next sibling in syntax tree
# s/S - MAJOR DIFF - regex select in selection/split in selection
# A-s - split on newlines 
C-s = ":write" # would be nice to have an autosave :|
# c-s/a-s - unmapped/unmapped
# -/_ - unmapped/trim whitespace from selection
# "-" = "toggle_comments # bug nopa nope
# '-' = "toggle_comments"
# '/' - last fuzzy picker/register operator
# ,/< - collapse multiple cursors/unindent
# ./> - repeat/indent
"A-." = ["save_selection","repeat_last_motion"] #  repeat last motion
# p/P - paste before/after
# a-p prev sibling in tree
# y/Y - yank selecton/Yank selection to clipboard
# f/F - seek til
f = ["save_selection", "find_next_char"]
F = ["save_selection", "find_prev_char"]
# g - goto operator/bottom (see below)
G = "goto_last_line" 
# c/C - change char/extend cursor down (change cursor down to operator?) 
C-c = [":w", "normal_mode"]
A-c = "toggle_comments" 
# r/R - replace char/not sure
# l/L - left/unmapped
# / ? - search fwd/back
# =/+ - format (core bug, disabled/unmapped
"=" = ":vsplit"
# \\/| - unmapped/pipe (call shell cmd)
"A-/" = ":vsplit"
"A-?" = ":hsplit"
# !/Alt-! similar to above
# ;/: - collapse selection/ex operand
# q/Q - apply macro/record macro
# j/J - vim default
# k/K - vim default/unclear
# x/X = bug: can't bind keys to extend_line_below, so keep this mapping; select line/select no wrap
# A-x shrink selection - unclear what do
# b/B - back/more back
# m/M - select-mode/unmapped
# w/W - fwd/more fwd
# "V" = "extend_line_below" # bug, will crash
V = ["save_selection","goto_line_start","select_mode", "goto_line_end"] 
# V = ["save_selection","goto_line_start","select_mode","move_line_down"] 
# C-V = "paste_clipboard_before" # bug: nope
# z/Z - adjust screen view mode/Sticky mode
"%" = ["save_selection", "select_all"] # also see %
# these cause helix to crash:
# a = ["save_selection", "append_to_line"] 
# A = ["save_selection", "append_to_line"]

# C-/ = "toggle_comments" # nope

[keys.normal.g] # goto should save jumplist position 
"."=["save_selection","goto_last_modification"]
y = ["save_selection","goto_type_definition"]
f = ["save_selection","goto_file"] # goto-file in selection, meh?
g = ["save_selection","goto_file_start"]
c = ["save_selection","goto_window_center"]
r = ["save_selection","goto_reference"]
l = ["save_selection","goto_line_end"]
L = ["save_selection","goto_line_end"]
a = ["save_selection","goto_last_accessed_file"]
o = "jump_backward"
i = "jump_forward"
I = ["save_selection","goto_implementation"]
d = ["save_selection","goto_definition"]
h = ["save_selection","goto_line_start"]
t = ["save_selection","goto_window_top"]
n = ["save_selection","goto_previous_buffer"]
s = ["save_selection","goto_first_nonwhitespace"]
b = ["save_selection","goto_window_bottom"]
m = ["save_selection","goto_last_modified_file"]

# Copy this section into C-t insert mode.
[keys.normal."C-t"] # toggles (maybe)

# [keys.normal."["]
# space = ["move_char_left", "insert_mode", "space", "normal_mode"]
# [keys.normal."]"]
# space = ["move_char_right", "insert_mode", "space", "normal_mode"]

[keys.normal."A-b"]
q = ":buffer-close" # also :bc
A-q = ":buffer-close!" # also :bc!
# c = ":vsplit-new scratch" # new buffer in split # bug - runtime error
C = ":new" # scratch buffer
n = ":buffer-next"
p = ":buffer-previous"
k = ":buffer-next"
j = ":buffer-previous"
s = ":write-all" # write all buffers

[keys.normal."C-m"]
f = ":fmt"

[keys.normal.space] # misc operators, temp
space = ":w"
p = "paste_clipboard_before" # swap these
P = "paste_clipboard_after"
q = ":wq"
# o = ":cd" # have to provide a dir

[keys.normal.space.c]
a = ":open ~/.files/fish/conf.d/alias.fish"
A = ":open ~/.files/alacritty/alacritty.yml"
b = ":open ~/.files/fish/conf.d/bind.fish"
c = ":config-open"
d = ":open ~/.files/install.conf.yaml"
f = ":open ~/.files/fish/config.fish"
l = ":open ~/.config/helix/languages.toml" 
K = ":open ~/.setup/clones/helix/book/src/keymap.md"
C = ":open ~/.setup/clones/helix/book/src/generated/typable-cmd.md"
s = ":open ~/.setup/install.sh"
u = ":open ~/.setup/unsorted.sh"
v = ":open ~/.files/vimrc"
V = ":open ~/note2/.obsidian.vimrc"
z = ":open ~/.zshrc" 
space = ":config-reload"

############
## SELECT ##
############
# Alt-o - expand selection to parent syntax note *useful*
# alt-n selects next sibling in syntax tree
# s/S - MAJOR DIFF - regex select in selection/split in selection
# Alt-s split on newlines
# & - align cursors
# _ - trim whitespace from selection
# ; - collapse selection 
# C - extend cursor down
# A-C - cursor up
# (,) - rotate primary cursor
# A-(/) - rotate selections (seems like this would b hard to use)
# % or C-a - select all
# K - keep selections matching regex (narrow selections)
# A-K - remove selections matching regex
# A-(hljk) - TS select next prev

[keys.select]
V = "move_line_down"
G = "goto_last_line" 
T = "switch_case"
C-c = "normal_mode"

#############
## INSERT ###
#############

[keys.insert]
C-c = [":w", "normal_mode"]
# j = { j = "normal_mode" } # more annoying in helix than vim
# k = { k = "normal_mode" }
