# My language configurations
# https://docs.helix-editor.com/languages.html

# support helix-gpt completions
[language-server.gpt]
command = "helix-gpt"

# https://github.com/rubydusa/circom-lsp
[language-server.circom-lsp]
command = "circom-lsp"

# [language-server.rust-analyzer.config]
# checkOnSave.command = "clippy" # d: "check"
# checkOnSave.allTargets = true # d: true
# checkOnSave.features = "all" # d: null

[[language]]
name       = "markdown"
file-types = ["md"]
text-width = 100

[[language]]
name             = "typescript"
language-servers = ["typescript-language-server", "gpt"]
auto-format      = true

[[language]]
name        = "toml"
formatter   = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name             = "rust"
language-servers = ["rust-analyzer", "gpt"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
'|' = '|'

[[language]]
name             = "circom"
scope            = "source.circom"
injection-regex  = "circom"
file-types       = ["circom"]
roots            = ["package.json"]
comment-tokens   = "//"
indent           = { tab-width = 4, unit = "    " }
auto-format      = false
language-servers = ["circom-lsp"]

[[grammar]]
name   = "circom"
source = { git = "https://github.com/Decurity/tree-sitter-circom", rev = "02150524228b1e6afef96949f2d6b7cc0aaf999e" }
