# My language configurations
# https://docs.helix-editor.com/languages.html

# support helix-gpt completions
[language-server.gpt]
command = "helix-gpt"

[language-server.ts]
command = "typescript-language-server"
args = ["--stdio"]
language-id = "javascript"

# https://github.com/rubydusa/circom-lsp
[language-server.circom-lsp]
command = "circom-lsp"
args = ["--stdio"]
# config = 
# environment = { "ENV1" = "value1", "ENV2" = "value2" }

# [language-server.rust-analyzer.config]
# checkOnSave.command = "clippy" # d: "check"
# checkOnSave.allTargets = true # d: true
# checkOnSave.features = "all" # d: null

[[language]] 
name = "markdown"
file-types = ["md"]
text-width = 100

[[language]]
name = "typescript"
language-servers = [ "ts", "gpt" ]

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "gpt" ]  

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
'|' = '|'

[[language]]
name = "circom"
scope = "source.circom"
injection-regex = "circom"
file-types = ["circom"]
roots = ["package.json"]
comment-tokens = "//"
indent = { tab-width = 4, unit = "    " }
auto-format = false
language-servers = ["circom-lsp"]
# "diagnostic.error" = { underline = { style = "curl", color = "red" } }

[[grammar]]
name = "circom"
source = { git = "https://github.com/Decurity/tree-sitter-circom", rev = "c4df0664be207e2eae9f5507f9f5f00ea0a952c9" }
