[[language]]
name = "markdown"
max-line-length = 100

[[language]]
name = "rust"

[config.rust-analyzer]
imports.granularity.enforce = "true"
checkOnSave.allTargets = "true"
checkOnSave.features = "all"

