# My language configurations
# https://docs.helix-editor.com/languages.html

[[language]] 
name = "markdown"
file-types = ["md"]
# :( no effect:
max-line-length = 100 

[[language]]
name = "rust"

[config.rust-analyzer]
imports.granularity.enforce = "true"
checkOnSave.allTargets = "true"
checkOnSave.features = "all"
# indent = { tab-width = "    " }

